[advisories]

[bans]
multiple-versions = "warn"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
